INTENTS = {
    "coach": ["coach", "coaches", "treinador", "treinadores", "trainer", "trainers"],
    "history": [
        "campeonatos",
        "títulos",
        "história",
        "tournaments",
        "torneios",
        "history",
        "conquistas",
        "legado",
        "legacy",
    ],
    "social": [
        "twitter",
        "instagram",
        "redes sociais",
        "X",
        "facebook",
        "loja",
        "store",
        "site",
        "rede",
        "redes",
        "links",
        "link",
        "site oficial",
        "twitch",
        "tiktok",
        "youtube",
        "canal",
    ],
    "roster": ["roster", "players", "jogadores", "time", "equipe", "atletas"],
    "facts": [
        "trivia",
        "curiosidades",
        "curiosidade",
        "fato",
        "fatos",
        "sabia",
        "interessante",
    ],
}
